#!/bin/bash
cd "/Users/user/Documents/instagram_api"
if [[ -f "setup.sh" ]]; then
    open -a Terminal "/Users/user/Documents/instagram_api/setup.sh"
else
    osascript -e 'display alert "Error" message "Script setup.sh not found in /Users/user/Documents/instagram_api"'
fi
